import Head from "next/head";
// import styles from "../styles/Home.module.css";
import { UserProvider } from "@auth0/nextjs-auth0";

function layout({ children }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <UserProvider>{children}</UserProvider>
    </>
  );
}

export default layout;
